In [1]:
# Import dependencies 
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import pickle

In [2]:
# Read CSV
df = pd.read_csv('../../../Data/articles.csv')
df.head(5)

Unnamed: 0  articlesid  fakeid  trueid  \
0           0           1     1.0     NaN   
1           1           2     2.0     NaN   
2           2           3     3.0     NaN   
3           3           4     4.0     NaN   
4           4           5     5.0     NaN   

                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text  subject  label  
0  Donald Trump just couldn t wish all Americans ...  US News      1  
1  House Intelligence Committee Chairman Devin Nu...  US News      1  
2  On Friday, it was revealed that former Milwauk...  US News      1  
3  On Christmas day, Donald Trump announced that ...  US News      1  
4  Pope Francis used his annual Christmas Day mes...  US News      1

In [3]:
# Drop unused columns in model testing
df = df[['title','text','label']]
df

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
37646  'Fully committed' NATO backs new U.S. approach...   
37647  LexisNexis withdrew two products from Chinese ...   
37648  Minsk cultural hub becomes haven from authorities   
37649  Vatican upbeat on possibility of Pope Francis ...   
37650  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text  label  
0      Donald Trump just couldn t wish all Americans ...      1  
1      House Intelligence Committee Chairman Devin Nu...      1  
2      On Friday, it was revealed that former Milwauk...      1  
3      On Christmas day, Donald Trump announced that ...      1  
4      Pope Francis used his annual Christmas Day mes...      1  
...                                                  ...    ...  
37646  BRUSSELS (Reuters) - NATO allies on Tuesday we...      0  
37647  LONDON (Reuters) - LexisNexis, a provider of l...      0  
37648  MINSK (Reuters) - In the shadow of disused Sov...      0  
37649  MOSCOW (Reuters) - Vatican Secretary of State ...      0  
37650  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      0  

[37651 rows x 3 columns]

In [30]:
# Defining the feature set X and y; model test on TEXT
X = df.text
y = df.label

# Split data into training and testing sets 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, test_size=0.20)

In [31]:
# Implement CountVectorizer which tokenizes and counts occurance of words in text
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)
X_test_count = cv.transform(X_test)

In [35]:
# Usng Multinomial algorithm of Naive Bayes for model training
model = MultinomialNB()
model.fit(X_train_count,y_train)
y_pred = model.predict(X_test_count)

In [36]:
# Finding the accuracy of the Multinomial Navie Bayes model
# MultinomialNB is suitable for classificaion with discrete features
model.score(y_pred,y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[0 1 1 ... 1 1 1].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
# Save model & countVectorizer to disk
pickle.dump(model, open('nb_model.sav', 'wb'))
pickle.dump(cv, open('cv.sav', 'wb'))

In [9]:
X_train.values

array(['WASHINGTON (Reuters) - When Jeb Hensarling, the Republican chair of the U.S. House Financial Services Committee, released legislation this summer to weaken the major financial law known as Dodd-Frank, many said it was a prêt-a-porter plan that his party’s nominee, Donald Trump, could easily adopt. Now that Trump is president-elect, he appears to be doing just that.  Language about financial services posted on the Trump transition website, www.greatagain.gov, echoes the tone of Hensarling’s bill, known as the CHOICE Act.  It calls Dodd-Frank, passed in the wake of the 2007-09 financial crisis and recession, as “a sprawling and complex piece of legislation that has unleashed hundreds of new rules and several new bureaucratic agencies” and promises to dismantle and replace it with “new policies to encourage economic growth and job creation.” Hensarling’s legislation, which his committee approved in September, also takes a replacement approach. The Texas Republican had unveiled his

In [37]:
y_pred

array([0, 1, 1, ..., 1, 1, 1])

In [17]:
y_test.values

array([0, 1, 1, ..., 1, 0, 1])

In [20]:
X_test_count.toarray()

array([[0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
X_test_count.toarray()

array([[0, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])